---
- name: Demonstrar uso de Vault
  hosts: local 
  vars_files: # Carrega variáveis de arquivo externos
    - secrets.yml

  tasks:
    - name: Mostrar usuario (seguro mostrar)
      debug:
        msg: "Usuario do banco: {{ db_user }}"

    - name: Mostrar senha mascarada
      debug:
        msg: "Senha tem {{ db_password | length }} caracteres" # Filtro Jinja2 que retorna tamanho

    - name: Simular uso da API key
      debug:
        msg: "API Key comeca com: {{ api_key[:6] }}..."  #  Slice do Python, pega primeiros 6 caracteres

    - name: Criar arquivo de config (exemplo real)
      copy:
        content: |
          DB_USER={{ db_user }}
          DB_PASS={{ db_password }}
          API_KEY={{ api_key }}
        dest: /tmp/app-config.env
        mode: '0600' # Só o dono pode ler/escrever